FROM golang:1.23-alpine AS build

WORKDIR /src
ENV GOWORK=off

COPY go.work ./
COPY common ./common
COPY client ./client

RUN go build -C client -o /out/client ./cmd/client

FROM alpine:3.20

RUN adduser -D -H appuser
USER appuser

COPY --from=build /out/client /usr/local/bin/client

ENTRYPOINT ["/usr/local/bin/client"]
